version: '3.8'

services:
  ets-features:
    image: ogccite/ets-ogcapi-features10
    container_name: ets-features
    ports:
      - "8082:8080"
    networks:
      - default

  ets-tiles:
    image: ogccite/ets-ogcapi-tiles10
    container_name: ets-tiles
    ports:
      - "8083:8080"
    networks:
      - default

networks:
  default:
    name: cite_default
    external: true
